name: 'dbt_northwind_trades'
version: '1.0.0'

profile: 'dbt_northwind_trades'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

### Seeds configuration ###

seeds:
  dbt_northwind_trades:
    +schema: seed

### Models configuration ###
models:
  dbt_northwind_trades:
    staging:
      +materialized: view
      +schema: staging
    
    mart:
      +materialized: table
      +schema: mart

### Tests Configuration 
tests:
  dbt_northwind_trades:
    +severity: warn
