name: 'dbt_northwind_trades'
version: '1.0.0'

profile: 'dbt_northwind_trades'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

models:
  dbt_northwind_trades:
    example:
      +materialized: view
